ApplETS/ETSMobile-Android2

- app/build.gradle
- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/NotesDetailsFragment.java
- app/src/main/res/layout/notes_details_fragment.xml
- gradlew
Resizing of course title and removal of the course acronym
> fixed issues Etsm_AND-26

- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/SponsorsFragment.java
> Fix bug when null sponsor URL

- app/build.gradle
- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/MoodleFragment.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/util/CourseComparator.java
- app/src/main/res/layout/row_moodle_course.xml
- gradlew
- settings.gradle
Dans ce fix, j'ai ré-arrangé l'ordre dans lesquelles les cours s'affiche dans l'onglet Moodle. Maintenant, peu importe dans quelle ordre le serveur nous envoie les cours, l'app va toujours les placés dans le bon ordre! De plus, j'ai éliminé le troncage dans le titre des cours dans MoodleFragment.
(Issue 8 et 15 régler)
> Steven moodle fix

- app/src/main/res/layout/notes_details_fragment.xml
> Fixed padding in note details

- app/src/main/java/ca/etsmtl/applets/etsmobile/model/ConsommationBP.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/model/ConsommationBandePassante.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/BandwithFragment.java
Le fragment bande passante fonctionne maintenant! J'ai testé avec des chambres de tous les 4 phases. Voici ce que ça donne:
> Steven bande passante

- app/build.gradle
- app/src/main/java/ca/etsmtl/applets/etsmobile/http/AppletsApiNewsRequest.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/model/NewsSource.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/model/Nouvelle.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/activity/NewsDetailsActivity.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/adapter/NewsAdapter.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/adapter/NewsSourceAdapter.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/NewsFragment.java
- app/src/main/res/layout/activity_news_details.xml
- app/src/main/res/layout/row_news.xml
- app/src/main/res/layout/row_news_source.xml
- app/src/main/res/values-en/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- build.gradle
J'ai passé environ 2 mois à tester la version et elle est sans bug. Je vais rajouter la feature maintenant et faire une release.
> Steven news

- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/TodayFragment.java
- app/src/main/res/drawable/semester_progress_bar_layer_list.xml
- app/src/main/res/layout/fragment_today.xml
- app/src/main/res/values-en/strings.xml
- app/src/main/res/values/strings.xml
Affichage de la progression de la session dans la vue Today
> Ajout barre de progression de la session

- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/BottinDetailsFragment.java
Règle la situation suivante:
https://github.com/ApplETS/ETSMobile-Android2/issues/55
> Fix pour liens téléphoniques

- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/HoraireFragment.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/util/AndroidCalendarManager.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/util/HoraireManager.java
- app/src/main/res/values-en/strings.xml
- app/src/main/res/values/strings.xml
Corrections apportées en fonction de la situation suivante:
https://github.com/ApplETS/ETSMobile-Android2/issues/58
Pour ce qui est de S Planner qui se fermait, j'avais la même situation lorsque que j'essayais de supprimer un événement crée par ETSMobile avec un certain Samsung G870A. Il ne semble plus y avoir de soucis avec celui-ci après application du changement énoncé. 
Resterait à confirmer le tout sur S Planner avec un Galaxy S7.
> Amélioration du calendrier

- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/activity/MainActivity.java
NullPointerException sur studentName
> fix student name null

- app/src/main/res/layout/fragment_about.xml
- app/src/main/res/values-en/strings.xml
- app/src/main/res/values/strings.xml
> Added ETSMobile repo link in About

- app/src/main/AndroidManifest.xml
- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/activity/MoodleCourseActivity.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/activity/UrgenceActivity.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/SecuriteFragment.java
- app/src/main/res/layout/urgence.xml
- Removed PDF features that weren't working and potentially not so useful
- Fix bad shifting when launching an activity related to a type of Urgence
- Fix Back action to return to the previous Security fragment when in a specific Urgence activity
> Fix Security

- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/BottinFragment.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/TodayFragment.java
- app/src/main/res/layout/calendar_horaire_layout.xml
- app/src/main/res/layout/fragment_note.xml
- app/src/main/res/layout/row_note_menu.xml
- Correction d'un problème où le SwipeRefreshLayout demeurait indéfiniment à l'état de rafraîchissement lorsqu'on consultait les détails alors que celui-ci n'était pas terminé
- Correction de marges pour éviter que la surbrillance et la barre de défilement soit trop espacée
- Affichage de la progression de la session lorsque l'appareil est hors-ligne
> Little fixes

- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/TodayFragment.java
- Le nombre de jours avant le début de la prochaine session n'était pas
affichée en mode hors-ligne.
- Un jour de trop était ajouté au nombre de jours total de la session.
> Fix semester's bar

- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/TodayFragment.java
-Ajout de la vérification de la taille de la liste de sessions
> Fix Semester Bar (2)

- app/src/main/res/values/webservices.xml
Fixe les problèmes de connexion avec Moodle depuis le 22 août dernier.
Note: Take 2 vu que le premier PR n'était pas satisfaisant.
> Moodle endpoints

- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/activity/LoginActivity.java
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/values-en/strings_activity_login.xml
- app/src/main/res/values/strings_activity_login.xml
-Ajout d'un message pour indiquer l'échec de la connexion au serveur
-Changement de couleur du message de connexion pour améliorer la visibilité
> Little fixes for login page

- app/build.gradle
- app/src/main/res/drawable/ic_notifications_white_24dp.xml
- app/src/main/res/menu/menu_today.xml
- build.gradle
- Retrait de l'icône des notifications de l'overflow menu pour améliorer la visibilité
- Changement de l'icône des notifications pour une cloche qui est un symbole commun
- Mise à jour de gradle
> Change notifications icon

- app/build.gradle
- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/activity/NotesDetailsActivity.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/NotesDetailsFragment.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/util/NoteManager.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/util/ProfilManager.java
Correction d'un problème de chargement perpétuel des notes sous Android 8
>  Fix ListeDesElementsEvaluation not returned

- app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/TodayFragment.java
- app/src/main/java/ca/etsmtl/applets/etsmobile/widget/TodayWidgetProvider.java
- app/src/main/res/values-en/plurals.xml
- app/src/main/res/values-en/strings.xml
- app/src/main/res/values/plurals.xml
- app/src/main/res/values/strings.xml
Le "1 jours" dans la photo du Spotted me fatiguait, voici le fix.
https://www.facebook.com/photo.php?fbid=1662257260500039&set=p.1662257260500039&type=3&theater
> Utilisation des resources plurals pour les journées restantes
